version: '3.7'
networks:
  milocal:
    driver: bridge

# Definimos los servicios
services:
  # Definimos la base de datos
  mysql:
    container_name: mysql_server
    image: mysql:5.7
    restart: always
    # Indicamos las variables de entorno con el usuario y contraseña.
    # Se recomienda usar variables de entorno en un fichero separado para no mostrar las credenciales en claro.
    # Pero al ser una prueba usaremos las credenciales en claro.
    environment:
      MYSQL_DATABASE: escuela
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    # Exponemos los puertos
    ports:
    - "3306:3306"
    volumes:
    - type: volume
      source: mysql_data
      target: /var/lib/mysql
    # Se definen las redes
    networks:
      - milocal
    # Nombre de la máquina
    hostname: mysql
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: drupal.logs
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    # Se definen las redes
    networks:
      - milocal
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: drupal.logs
volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind