version: '3.7'

# Definimos la red
networks:
  mired:
    driver: bridge

# Definimos los servicios
services:
  # Definimos la base de datos
  mysql:
    container_name: mysql_server
    image: ${MYSQL_IMAGE}
    restart: always
    # Indicamos las variables de entorno con el usuario y contraseña.
    # Se recomienda usar variables de entorno en un fichero separado para no mostrar las credenciales en claro.
    # Pero al ser una prueba usaremos las credenciales en claro.
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # Exponemos los puertos
    ports:
    - "3306:3306"
    volumes:
    - type: volume
      source: mysql_data
      target: /var/lib/mysql
    # Se definen las redes
    networks:
      - mired
    # Nombre de la máquina
    hostname: mysql
  
  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE}
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    # Se definen las redes
    networks:
      - mired

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind